# DIAMONDS - BLUE
ace_d = Card.new(:diamonds, 11, "Ace of Diamonds")
two_d = Card.new(:diamonds, 2, "Two of Diamonds")
three_d = Card.new(:diamonds, 3, "Three of Diamonds")
four_d = Card.new(:diamonds, 4, "Four of Diamonds")
five_d = Card.new(:diamonds, 5, "Five of Diamonds")
six_d = Card.new(:diamonds, 6, "Six of Diamonds")
seven_d = Card.new(:diamonds, 7, "Seven of Diamonds")
eight_d = Card.new(:diamonds, 8, "Eight of Diamonds")
nine_d = Card.new(:diamonds, 9, "Nine of Diamonds")
ten_d = Card.new(:diamonds, 10, "Ten of Diamonds")
jack_d = Card.new(:diamonds, 10, "Jack of Diamonds")
queen_d = Card.new(:diamonds, 10, "Queen of Diamonds")
king_d = Card.new(:diamonds, 10, "king of Diamonds")

# SPADES - BLACK
ace_s = Card.new(:spades, 11, "Ace of Spades")
two_s = Card.new(:spades, 2, "Two of Spades")
three_s = Card.new(:spades, 3, "Three of Spades")
four_s = Card.new(:spades, 4, "Four of Spades")
five_s = Card.new(:spades, 5, "Five of Spades")
six_s = Card.new(:spades, 6, "Six of Spades")
seven_s = Card.new(:spades, 7, "Seven of Spades")
eight_s = Card.new(:spades, 8, "Eight of Spades")
nine_s = Card.new(:spades, 9, "Nine of Spades")
ten_s = Card.new(:spades, 10, "Ten of Spades")
jack_s = Card.new(:spades, 10, "Jack of Spades")
queen_s = Card.new(:spades, 10, "Queen of Spades")
king_s = Card.new(:spades, 10, "king of Spades")

# HEARTS - RED
ace_h = Card.new(:hearts, 11, "Ace of Hearts")
two_h = Card.new(:hearts, 2, "Two of Hearts")
three_h = Card.new(:hearts, 3, "Three of Hearts")
four_h = Card.new(:hearts, 4, "Four of Hearts")
five_h = Card.new(:hearts, 5, "Five of Hearts")
six_h = Card.new(:hearts, 6, "Six of Hearts")
seven_h = Card.new(:hearts, 7, "Seven of Hearts")
eight_h = Card.new(:hearts, 8, "Eight of Hearts")
nine_h = Card.new(:hearts, 9, "Nine of Hearts")
ten_h = Card.new(:hearts, 10, "Ten of Hearts")
jack_h = Card.new(:hearts, 10, "Jack of Hearts")
queen_h = Card.new(:hearts, 10, "Queen of Hearts")
king_h = Card.new(:hearts, 10, "king of Hearts")

# Clubs - GREEN
ace_c = Card.new(:clubs, 11, "Ace of Clubs")
two_c = Card.new(:clubs, 2, "Two of Clubs")
three_c = Card.new(:clubs, 3, "Three of Clubs")
four_c = Card.new(:clubs, 4, "Four of Clubs")
five_c = Card.new(:clubs, 5, "Five of Clubs")
six_c = Card.new(:clubs, 6, "Six of Clubs")
seven_c = Card.new(:clubs, 7, "Seven of Clubs")
eight_c = Card.new(:clubs, 8, "Eight of Clubs")
nine_c = Card.new(:clubs, 9, "Nine of Clubs")
ten_c = Card.new(:clubs, 10, "Ten of Clubs")
jack_c = Card.new(:clubs, 10, "Jack of Clubs")
queen_c = Card.new(:clubs, 10, "Queen of Clubs")
king_c = Card.new(:clubs, 10, "king of Clubs")
